#!/usr/bin/python

import json
import requests
import sys

MOPIDY_ADDRESS = "http://localhost:6680/mopidy/rpc"

def do_rpc(method):
    try:
        r = requests.post(MOPIDY_ADDRESS, data = '{"jsonrpc": "2.0", "id": 1, "method": "%s"}' % method)
        return json.loads(r.text)
    except:
        sys.stderr.write("no mopidy lol\n")

def pause():
    do_rpc("core.playback.pause")

def resume():
    do_rpc("core.playback.resume")

def next():
    do_rpc("core.playback.next")

def previous():
    do_rpc("core.playback.previous")

def toggle_play_pause():
    if do_rpc("core.playback.get_state")["result"] == "playing":
        pause()
    else:
        resume()

ACTIONS = {
    "pause": pause,
    "resume": resume,
    "next": next,
    "previous": previous,
    "toggle_play_pause": toggle_play_pause
}

def possible_actions():
    return ", ".join(map(lambda s: "'%s'" % s, ACTIONS.keys()))

if len(sys.argv) < 2:
    sys.exit("Usage: mopidy-cli <action>.\nNo action given.")

action = ACTIONS.get(sys.argv[1])

if action:
    action()
else:
    sys.exit("Error: Invalid action '%s'. Possible actions: %s" %
             (sys.argv[1], possible_actions()))
