#!/bin/bash

# Crude power management/locking utility script

set -e

case "$1" in
	lock)
		sc=$(mktemp -u).png
		mopidy-cli pause &
		maim $sc
		# Pixelate screenshot
		convert $sc -scale 10% -scale 1000% $sc
		i3lock -i $sc -e --statusfont="Fantasque Sans Mono" --insidecolor=00000066 --line-uses-inside --ringcolor=00000088 --keyhlcolor=16a04f88 --separatorcolor=00000000 --ringwrongcolor=bd2c40ff --insidewrongcolor=bd2c4066 --ringvercolor=0e407bff --insidevercolor=0e407b66 --textcolor=ffffffaa --veriftext=... --wrongtext=nope --radius 120 --bshlcolor=bd2c40ff
		rm $sc
		;;
	suspend)
		bash $0 lock
		systemctl suspend
		;;
	hibernate)
		bash $0 lock
		systemctl hibernate
		;;
	logout)
		i3-msg exit
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
		echo "Usage: $0 {lock|suspend|hibernate|logout|reboot|shutdown}" 1>&2
		exit 1
esac
