#!/bin/bash

increments="5%"

# Get default sink name
sink=$(pactl info | grep -i "default sink" | cut -d ' ' -f 3)

case "$1" in
	up)
		pactl set-sink-volume $sink "+$increments"
		;;
	down)
		pactl set-sink-volume $sink "-$increments"
		;;
	mute)
		pactl set-sink-mute $sink toggle
		;;
	*)
		echo "Usage: $0 {up|down|mute}" 1>&2
		exit 1
esac
